# Generated by Django 5.2.14 on 2026-05-28 13:31

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("inventory", "0001_initial"),
        ("stores", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "full_name",
                    models.CharField(help_text="Customer full name.", max_length=255),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, help_text="Primary phone number.", max_length=32
                    ),
                ),
                (
                    "extra_phone",
                    models.CharField(
                        blank=True, help_text="Additional phone number.", max_length=32
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, help_text="Customer address."),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Current customer debt balance.",
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "bonus_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Customer bonus balance for future loyalty use.",
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether the customer is active."
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Internal customer notes."),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["full_name"], name="sales_custo_full_na_89a82f_idx"
                    ),
                    models.Index(fields=["phone"], name="sales_custo_phone_43e3c6_idx"),
                    models.Index(
                        fields=["is_active"], name="sales_custo_is_acti_1b1d19_idx"
                    ),
                    models.Index(
                        fields=["balance"], name="sales_custo_balance_26e7e1_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "receipt_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Generated receipt number.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "sale_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Sale date and time.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("REFUNDED", "Refunded"),
                        ],
                        default="DRAFT",
                        help_text="Current sale workflow status.",
                        max_length=20,
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Sum of sale item totals before sale-level discount and tax.",
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Sale-level discount amount.",
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Sale-level tax amount.",
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Final sale amount after discount and tax.",
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Paid amount excluding debt allocations.",
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "remaining_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Remaining customer debt for this sale.",
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("note", models.TextField(blank=True, help_text="Sale note.")),
                (
                    "branch",
                    models.ForeignKey(
                        help_text="Branch where the sale happened.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales",
                        to="stores.branch",
                    ),
                ),
                (
                    "cashier",
                    models.ForeignKey(
                        help_text="Cashier who created or completed the sale.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional customer for debt and loyalty tracking.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales",
                        to="sales.customer",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        help_text="Warehouse that supplies stock for this sale.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales",
                        to="inventory.warehouse",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Refund",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "refund_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Refund date and time.",
                    ),
                ),
                ("reason", models.TextField(help_text="Refund reason.")),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total refund amount.",
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "cashier",
                    models.ForeignKey(
                        help_text="Cashier who created the refund.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refunds",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "original_sale",
                    models.ForeignKey(
                        help_text="Original sale being refunded.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refunds",
                        to="sales.sale",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SaleItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Sold quantity.",
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.001"))
                        ],
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Unit sale price.",
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Item-level discount amount.",
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Calculated item total.",
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Sold product.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale_items",
                        to="catalog.product",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        help_text="Sale this item belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="sales.sale",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SalePayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("CARD", "Card"),
                            ("CLICK", "Click"),
                            ("PAYME", "Payme"),
                            ("DEBT", "Debt"),
                            ("MIXED", "Mixed"),
                        ],
                        default="CASH",
                        help_text="Payment method used.",
                        max_length=32,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Payment amount.",
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("note", models.TextField(blank=True, help_text="Payment note.")),
                (
                    "paid_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Payment date and time.",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        help_text="Sale this payment belongs to.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="sales.sale",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CustomerPayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Payment amount.",
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("CARD", "Card"),
                            ("BANK_TRANSFER", "Bank transfer"),
                            ("CLICK", "Click"),
                            ("PAYME", "Payme"),
                            ("OTHER", "Other"),
                        ],
                        default="CASH",
                        help_text="Payment method used.",
                        max_length=32,
                    ),
                ),
                ("note", models.TextField(blank=True, help_text="Payment note.")),
                (
                    "paid_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Payment date and time.",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who recorded this customer payment.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customer_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        help_text="Customer making the debt payment.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="sales.customer",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["customer", "paid_at"],
                        name="sales_custo_custome_fcf78e_idx",
                    ),
                    models.Index(
                        fields=["payment_method", "paid_at"],
                        name="sales_custo_payment_1d08e6_idx",
                    ),
                    models.Index(
                        fields=["created_by", "paid_at"],
                        name="sales_custo_created_cebd30_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="LoyaltyAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "points",
                    models.PositiveIntegerField(
                        default=0, help_text="Current loyalty points."
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        default="standard", help_text="Loyalty level.", max_length=64
                    ),
                ),
                (
                    "total_spent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total completed sale amount for loyalty calculations.",
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "customer",
                    models.OneToOneField(
                        help_text="Customer attached to this loyalty account.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loyalty_account",
                        to="sales.customer",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
                "indexes": [
                    models.Index(fields=["level"], name="sales_loyal_level_8cdee0_idx"),
                    models.Index(
                        fields=["total_spent"], name="sales_loyal_total_s_14d5a3_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RefundItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Refunded quantity.",
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.001"))
                        ],
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Refund amount for this item.",
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Refunded product.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refund_items",
                        to="catalog.product",
                    ),
                ),
                (
                    "refund",
                    models.ForeignKey(
                        help_text="Refund this item belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="sales.refund",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["refund", "product"],
                        name="sales_refun_refund__4e39b7_idx",
                    ),
                    models.Index(
                        fields=["product"], name="sales_refun_product_c3d3ef_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(
                fields=["receipt_number"], name="sales_sale_receipt_f5ff95_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(
                fields=["status", "sale_date"], name="sales_sale_status_7f16d7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(
                fields=["branch", "status"], name="sales_sale_branch__2960d8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(
                fields=["warehouse", "status"], name="sales_sale_warehou_7956af_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(
                fields=["cashier", "sale_date"], name="sales_sale_cashier_a6082b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(
                fields=["customer", "sale_date"], name="sales_sale_custome_e35bee_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="sale",
            constraint=models.CheckConstraint(
                condition=models.Q(("subtotal__gte", Decimal("0.00"))),
                name="sale_subtotal_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="sale",
            constraint=models.CheckConstraint(
                condition=models.Q(("discount_amount__gte", Decimal("0.00"))),
                name="sale_discount_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="sale",
            constraint=models.CheckConstraint(
                condition=models.Q(("tax_amount__gte", Decimal("0.00"))),
                name="sale_tax_amount_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="sale",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_amount__gte", Decimal("0.00"))),
                name="sale_total_amount_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="sale",
            constraint=models.CheckConstraint(
                condition=models.Q(("paid_amount__gte", Decimal("0.00"))),
                name="sale_paid_amount_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="sale",
            constraint=models.CheckConstraint(
                condition=models.Q(("remaining_amount__gte", Decimal("0.00"))),
                name="sale_remaining_amount_non_negative",
            ),
        ),
        migrations.AddIndex(
            model_name="refund",
            index=models.Index(
                fields=["original_sale", "refund_date"],
                name="sales_refun_origina_eef459_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="refund",
            index=models.Index(
                fields=["cashier", "refund_date"], name="sales_refun_cashier_4b9e60_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="saleitem",
            index=models.Index(
                fields=["sale", "product"], name="sales_salei_sale_id_17278e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="saleitem",
            index=models.Index(
                fields=["product"], name="sales_salei_product_f87493_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salepayment",
            index=models.Index(
                fields=["sale", "paid_at"], name="sales_salep_sale_id_b37f03_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salepayment",
            index=models.Index(
                fields=["payment_method", "paid_at"],
                name="sales_salep_payment_20cfb3_idx",
            ),
        ),
    ]
