# Generated by Django 5.2.14 on 2026-05-29 04:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_stock_inventory_s_warehou_1119b6_idx_and_more"),
        ("sales", "0002_customerpayment_cashbox_and_more"),
        ("stores", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(
                fields=["branch", "status", "sale_date"],
                name="sales_sale_branch__3e9a2f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(
                fields=["cashier", "status", "sale_date"],
                name="sales_sale_cashier_ec1727_idx",
            ),
        ),
    ]
