# Generated by Django 5.2.14 on 2026-05-29 15:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_stock_inventory_s_warehou_1119b6_idx_and_more"),
        ("sales", "0003_sale_sales_sale_branch__3e9a2f_idx_and_more"),
        ("stores", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="idempotency_key",
            field=models.CharField(
                blank=True,
                help_text="Optional client-generated key used to safely retry checkout creation.",
                max_length=128,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(
                fields=["idempotency_key"], name="sales_sale_idempot_e1608d_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="sale",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key__isnull", False)),
                fields=("idempotency_key",),
                name="unique_sale_idempotency_key",
            ),
        ),
    ]
