# Generated by Codex on 2026-06-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0004_sale_idempotency_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="idempotency_fingerprint",
            field=models.CharField(
                blank=True,
                help_text="Hash of the checkout payload used to detect unsafe idempotency key reuse.",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(
                fields=["idempotency_fingerprint"],
                name="sales_sale_idempot_cecc9d_idx",
            ),
        ),
    ]
