# Generated by Django 5.2.14 on 2026-05-28 12:50

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "name",
                    models.CharField(help_text="Public store name.", max_length=255),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Store logo image.",
                        null=True,
                        upload_to="stores/logos/",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Primary store phone number.",
                        max_length=32,
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, help_text="Main store address."),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether the store is active."
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="User who owns this store.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stores",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("name", models.CharField(help_text="Branch name.", max_length=255)),
                ("address", models.TextField(blank=True, help_text="Branch address.")),
                (
                    "phone",
                    models.CharField(
                        blank=True, help_text="Branch phone number.", max_length=32
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether the branch is active."
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        help_text="Manager responsible for the branch.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_branches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        help_text="Store this branch belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branches",
                        to="stores.store",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CashDesk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Cash desk display name.", max_length=255
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique cash desk code inside the branch.",
                        max_length=64,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether the cash desk is active."
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        help_text="Branch where this cash desk operates.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cash_desks",
                        to="stores.branch",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["branch", "is_active"],
                        name="stores_cash_branch__8c0a5b_idx",
                    ),
                    models.Index(fields=["code"], name="stores_cash_code_212fcd_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("deleted_at__isnull", True)),
                        fields=("branch", "code"),
                        name="unique_active_cashdesk_code_per_branch",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="store",
            index=models.Index(fields=["name"], name="stores_stor_name_988b60_idx"),
        ),
        migrations.AddIndex(
            model_name="store",
            index=models.Index(
                fields=["owner", "is_active"], name="stores_stor_owner_i_c27bad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="branch",
            index=models.Index(
                fields=["store", "is_active"], name="stores_bran_store_i_5b4de8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="branch",
            index=models.Index(fields=["name"], name="stores_bran_name_32d097_idx"),
        ),
        migrations.AddConstraint(
            model_name="branch",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("store", "name"),
                name="unique_active_branch_name_per_store",
            ),
        ),
    ]
