# Generated by Django 5.2.14 on 2026-05-28 18:44

import uuid

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stores", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IntegrationProvider",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "code",
                    models.SlugField(
                        help_text="Stable provider code, for example uzum_market or telegram_bot.",
                        max_length=128,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Readable provider name.", max_length=255
                    ),
                ),
                (
                    "provider_type",
                    models.CharField(
                        choices=[
                            ("fiscal_check", "Fiscal/check system"),
                            ("receipt_printer", "Receipt printer"),
                            ("uzum_market", "Uzum Market"),
                            ("payment_provider", "Payment provider"),
                            ("telegram", "Telegram"),
                            ("sms", "SMS"),
                            ("offline_sync", "Offline sync"),
                            ("central_licensing", "Central licensing"),
                            ("other", "Other"),
                        ],
                        help_text="Integration category placeholder.",
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("disabled", "Disabled"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "base_url",
                    models.URLField(
                        blank=True,
                        help_text="Optional remote API base URL. Real API calls are not implemented yet.",
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Non-secret provider settings and feature flags.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional branch scope for branch-specific integrations.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="integration_providers",
                        to="stores.branch",
                    ),
                ),
            ],
            options={
                "verbose_name": "integration provider",
                "verbose_name_plural": "integration providers",
                "ordering": ("name",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="IntegrationCredential",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Credential key, for example api_key, token, username, or password.",
                        max_length=128,
                    ),
                ),
                (
                    "value",
                    models.TextField(
                        help_text="Credential value. Never expose this through API responses or admin lists."
                    ),
                ),
                ("is_secret", models.BooleanField(default=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_integration_credentials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credentials",
                        to="integrations.integrationprovider",
                    ),
                ),
            ],
            options={
                "verbose_name": "integration credential",
                "verbose_name_plural": "integration credentials",
                "ordering": ("provider__name", "key"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ExternalMapping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "local_model",
                    models.CharField(
                        help_text="Local model label, for example catalog.Product.",
                        max_length=128,
                    ),
                ),
                ("local_id", models.UUIDField()),
                ("external_id", models.CharField(max_length=255)),
                (
                    "external_type",
                    models.CharField(
                        blank=True,
                        help_text="External entity type, for example product, order, or receipt.",
                        max_length=128,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_mappings",
                        to="integrations.integrationprovider",
                    ),
                ),
            ],
            options={
                "verbose_name": "external mapping",
                "verbose_name_plural": "external mappings",
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="IntegrationTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "task_type",
                    models.CharField(
                        help_text="Placeholder task type, for example sync_products or send_receipt.",
                        max_length=128,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("retrying", "Retrying"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("inbound", "Inbound"), ("outbound", "Outbound")],
                        default="outbound",
                        max_length=16,
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("result", models.JSONField(blank=True, default=dict)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                (
                    "max_attempts",
                    models.PositiveSmallIntegerField(
                        default=3,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("next_retry_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_integration_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="integrations.integrationprovider",
                    ),
                ),
            ],
            options={
                "verbose_name": "integration task",
                "verbose_name_plural": "integration tasks",
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SyncLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("retrying", "Retrying"),
                        ],
                        db_index=True,
                        default="started",
                        max_length=16,
                    ),
                ),
                ("operation", models.CharField(max_length=128)),
                ("message", models.CharField(blank=True, max_length=255)),
                ("request_payload", models.JSONField(blank=True, default=dict)),
                ("response_payload", models.JSONField(blank=True, default=dict)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("error_message", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_logs",
                        to="integrations.integrationprovider",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sync_logs",
                        to="integrations.integrationtask",
                    ),
                ),
            ],
            options={
                "verbose_name": "sync log",
                "verbose_name_plural": "sync logs",
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("event_type", models.CharField(max_length=128)),
                ("external_event_id", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                            ("ignored", "Ignored"),
                        ],
                        db_index=True,
                        default="received",
                        max_length=16,
                    ),
                ),
                ("headers", models.JSONField(blank=True, default=dict)),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "signature",
                    models.CharField(
                        blank=True,
                        help_text="Webhook signature placeholder. Real verification is deferred.",
                        max_length=255,
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhook_events",
                        to="integrations.integrationprovider",
                    ),
                ),
            ],
            options={
                "verbose_name": "webhook event",
                "verbose_name_plural": "webhook events",
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="integrationprovider",
            index=models.Index(fields=["code"], name="integration_code_6fb775_idx"),
        ),
        migrations.AddIndex(
            model_name="integrationprovider",
            index=models.Index(
                fields=["provider_type", "status"],
                name="integration_provide_f7268f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="integrationprovider",
            index=models.Index(
                fields=["branch", "is_active"], name="integration_branch__3975d2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="integrationcredential",
            index=models.Index(
                fields=["provider", "key"], name="integration_provide_31d1ec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="integrationcredential",
            index=models.Index(
                fields=["expires_at"], name="integration_expires_cbf4f0_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="integrationcredential",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("provider", "key"),
                name="unique_active_integration_credential_key",
            ),
        ),
        migrations.AddIndex(
            model_name="externalmapping",
            index=models.Index(
                fields=["provider", "local_model", "local_id"],
                name="integration_provide_781495_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="externalmapping",
            index=models.Index(
                fields=["provider", "external_id"],
                name="integration_provide_c70b99_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="externalmapping",
            index=models.Index(
                fields=["external_type"], name="integration_externa_e777ab_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="externalmapping",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("provider", "local_model", "local_id"),
                name="unique_active_external_mapping_local",
            ),
        ),
        migrations.AddConstraint(
            model_name="externalmapping",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("provider", "external_id"),
                name="unique_active_external_mapping_external",
            ),
        ),
        migrations.AddIndex(
            model_name="integrationtask",
            index=models.Index(
                fields=["provider", "status"], name="integration_provide_5479d2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="integrationtask",
            index=models.Index(
                fields=["task_type", "status"], name="integration_task_ty_33a085_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="integrationtask",
            index=models.Index(
                fields=["next_retry_at"], name="integration_next_re_0870d3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="synclog",
            index=models.Index(
                fields=["provider", "status", "created_at"],
                name="integration_provide_09f9b0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="synclog",
            index=models.Index(
                fields=["operation", "created_at"],
                name="integration_operati_bb8878_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="webhookevent",
            index=models.Index(
                fields=["provider", "status", "received_at"],
                name="integration_provide_0030b6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="webhookevent",
            index=models.Index(
                fields=["event_type", "received_at"],
                name="integration_event_t_da57b5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="webhookevent",
            index=models.Index(
                fields=["external_event_id"], name="integration_externa_3fc8fb_idx"
            ),
        ),
    ]
