# Generated by Django 5.2.14 on 2026-06-17 16:05

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI chat session',
                'verbose_name_plural': 'AI chat sessions',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AIChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=20)),
                ('content', models.TextField()),
                ('intent', models.CharField(blank=True, choices=[('sales_today', 'Sales Today'), ('product_stock', 'Product Stock'), ('low_stock', 'Low Stock'), ('top_products', 'Top Products'), ('product_price', 'Product Price'), ('unknown', 'Unknown')], max_length=64)),
                ('confidence', models.FloatField(default=0.0)),
                ('entities', models.JSONField(blank=True, default=dict)),
                ('tool_name', models.CharField(blank=True, max_length=128)),
                ('tool_result', models.JSONField(blank=True, default=dict)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_assistant.aichatsession')),
            ],
            options={
                'verbose_name': 'AI chat message',
                'verbose_name_plural': 'AI chat messages',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AIFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('rating', models.CharField(choices=[('good', 'Good'), ('bad', 'Bad')], max_length=16)),
                ('comment', models.TextField(blank=True)),
                ('message', models.ForeignKey(limit_choices_to={'role': 'assistant'}, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='ai_assistant.aichatmessage')),
            ],
            options={
                'verbose_name': 'AI feedback',
                'verbose_name_plural': 'AI feedback',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AITrainingExample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('text', models.TextField()),
                ('intent', models.CharField(choices=[('sales_today', 'Sales Today'), ('product_stock', 'Product Stock'), ('low_stock', 'Low Stock'), ('top_products', 'Top Products'), ('product_price', 'Product Price'), ('unknown', 'Unknown')], max_length=64)),
                ('entities', models.JSONField(blank=True, default=dict)),
                ('expected_answer', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'AI training example',
                'verbose_name_plural': 'AI training examples',
                'ordering': ('-created_at',),
                'abstract': False,
                'indexes': [models.Index(fields=['intent', 'is_active'], name='ai_assistan_intent_32ff6a_idx'), models.Index(fields=['created_at'], name='ai_assistan_created_63bd42_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='aichatsession',
            index=models.Index(fields=['user', 'is_active'], name='ai_assistan_user_id_f2e64e_idx'),
        ),
        migrations.AddIndex(
            model_name='aichatsession',
            index=models.Index(fields=['updated_at'], name='ai_assistan_updated_a60ede_idx'),
        ),
        migrations.AddIndex(
            model_name='aichatmessage',
            index=models.Index(fields=['session', 'created_at'], name='ai_assistan_session_afb89a_idx'),
        ),
        migrations.AddIndex(
            model_name='aichatmessage',
            index=models.Index(fields=['role', 'created_at'], name='ai_assistan_role_14830e_idx'),
        ),
        migrations.AddIndex(
            model_name='aichatmessage',
            index=models.Index(fields=['intent'], name='ai_assistan_intent_df8f77_idx'),
        ),
        migrations.AddIndex(
            model_name='aifeedback',
            index=models.Index(fields=['message', 'rating'], name='ai_assistan_message_ae6a5c_idx'),
        ),
        migrations.AddIndex(
            model_name='aifeedback',
            index=models.Index(fields=['created_at'], name='ai_assistan_created_b8df3b_idx'),
        ),
    ]
