# Generated by Django 5.2.14 on 2026-06-18 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aichatmessage',
            name='intent',
            field=models.CharField(blank=True, choices=[('sales_today', 'Sales Today'), ('sales_month', 'Sales Month'), ('product_stock', 'Product Stock'), ('low_stock', 'Low Stock'), ('top_products', 'Top Products'), ('product_price', 'Product Price'), ('cashier_activity', 'Cashier Activity'), ('finance_summary', 'Finance Summary'), ('customer_debt', 'Customer Debt'), ('reports_summary', 'Reports Summary'), ('help', 'Help'), ('unknown', 'Unknown')], max_length=64),
        ),
        migrations.AlterField(
            model_name='aitrainingexample',
            name='intent',
            field=models.CharField(choices=[('sales_today', 'Sales Today'), ('sales_month', 'Sales Month'), ('product_stock', 'Product Stock'), ('low_stock', 'Low Stock'), ('top_products', 'Top Products'), ('product_price', 'Product Price'), ('cashier_activity', 'Cashier Activity'), ('finance_summary', 'Finance Summary'), ('customer_debt', 'Customer Debt'), ('reports_summary', 'Reports Summary'), ('help', 'Help'), ('unknown', 'Unknown')], max_length=64),
        ),
    ]
