# Generated by Django 5.2.14 on 2026-06-18 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0002_alter_aichatmessage_intent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aichatmessage',
            name='source',
            field=models.CharField(blank=True, choices=[('tool', 'Tool'), ('fallback', 'Fallback'), ('permission_denied', 'Permission Denied'), ('not_supported', 'Not Supported'), ('error', 'Error'), ('help', 'Help')], max_length=32),
        ),
        migrations.AddField(
            model_name='aifeedback',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_feedback', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='aichatmessage',
            index=models.Index(fields=['source', 'created_at'], name='ai_assistan_source_08c361_idx'),
        ),
        migrations.AddIndex(
            model_name='aifeedback',
            index=models.Index(fields=['created_by', 'created_at'], name='ai_assistan_created_fd26c0_idx'),
        ),
        migrations.AddConstraint(
            model_name='aifeedback',
            constraint=models.UniqueConstraint(condition=models.Q(('created_by__isnull', False), ('deleted_at__isnull', True)), fields=('message', 'created_by'), name='unique_ai_feedback_per_user_message'),
        ),
    ]
