# Generated by Django 5.2.14 on 2026-05-28 12:50

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("stores", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("name", models.CharField(help_text="Warehouse name.", max_length=255)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether the warehouse is active."
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        help_text="Branch that owns this warehouse.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warehouses",
                        to="stores.branch",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("IN", "In"),
                            ("OUT", "Out"),
                            ("TRANSFER", "Transfer"),
                            ("ADJUSTMENT", "Adjustment"),
                        ],
                        help_text="Type of stock movement.",
                        max_length=20,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Quantity moved. For adjustments this is the absolute changed amount.",
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.001"))
                        ],
                    ),
                ),
                (
                    "note",
                    models.TextField(blank=True, help_text="Optional movement note."),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who initiated the movement.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_movements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Product affected by the movement.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_movements",
                        to="catalog.product",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        help_text="Warehouse affected by the movement.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_movements",
                        to="inventory.warehouse",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0.000"),
                        help_text="Current physical stock quantity.",
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.000"))
                        ],
                    ),
                ),
                (
                    "reserved_quantity",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0.000"),
                        help_text="Quantity reserved for pending operations.",
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.000"))
                        ],
                    ),
                ),
                (
                    "low_stock_limit",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0.000"),
                        help_text="Threshold used for low stock alerts.",
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.000"))
                        ],
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Product held in stock.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stocks",
                        to="catalog.product",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        help_text="Warehouse holding the stock.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stocks",
                        to="inventory.warehouse",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InventoryAdjustment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True, help_text="Adjustment note or reason."
                    ),
                ),
                (
                    "adjustment_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Date and time of the stock count or adjustment.",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created the adjustment.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_adjustments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        help_text="Warehouse where the inventory adjustment was counted.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_adjustments",
                        to="inventory.warehouse",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="warehouse",
            index=models.Index(
                fields=["branch", "is_active"], name="inventory_w_branch__89a748_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="warehouse",
            index=models.Index(fields=["name"], name="inventory_w_name_703b74_idx"),
        ),
        migrations.AddConstraint(
            model_name="warehouse",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("branch", "name"),
                name="unique_active_warehouse_name_per_branch",
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["warehouse", "product", "created_at"],
                name="inventory_s_warehou_781dd3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["movement_type", "created_at"],
                name="inventory_s_movemen_ed5291_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["created_by", "created_at"],
                name="inventory_s_created_ea4848_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stock",
            index=models.Index(
                fields=["warehouse", "product"], name="inventory_s_warehou_58977a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stock",
            index=models.Index(
                fields=["product"], name="inventory_s_product_4c1da7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stock",
            index=models.Index(
                fields=["updated_at"], name="inventory_s_updated_1e6d45_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="stock",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("warehouse", "product"),
                name="unique_active_stock_per_warehouse_product",
            ),
        ),
        migrations.AddConstraint(
            model_name="stock",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", Decimal("0.000"))),
                name="stock_quantity_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="stock",
            constraint=models.CheckConstraint(
                condition=models.Q(("reserved_quantity__gte", Decimal("0.000"))),
                name="stock_reserved_quantity_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="stock",
            constraint=models.CheckConstraint(
                condition=models.Q(("low_stock_limit__gte", Decimal("0.000"))),
                name="stock_low_limit_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="stock",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", models.F("reserved_quantity"))),
                name="stock_quantity_covers_reserved_quantity",
            ),
        ),
        migrations.AddIndex(
            model_name="inventoryadjustment",
            index=models.Index(
                fields=["warehouse", "adjustment_date"],
                name="inventory_i_warehou_f17dfc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="inventoryadjustment",
            index=models.Index(
                fields=["created_by", "adjustment_date"],
                name="inventory_i_created_2b9ea1_idx",
            ),
        ),
    ]
