# Generated by Django 5.2.14 on 2026-05-28 13:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
        ("inventory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="stockmovement",
            name="expiry_date",
            field=models.DateField(
                blank=True,
                help_text="Optional expiry date for products that require expiry tracking.",
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["product", "expiry_date"], name="inventory_s_product_b4f761_idx"
            ),
        ),
    ]
