# Generated by Django 5.2.14 on 2026-05-29 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
        ("inventory", "0002_stockmovement_expiry_date_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="stock",
            index=models.Index(
                fields=["warehouse", "updated_at"],
                name="inventory_s_warehou_1119b6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stock",
            index=models.Index(
                fields=["quantity", "low_stock_limit"],
                name="inventory_s_quantit_b843e4_idx",
            ),
        ),
    ]
