# Generated by Django 5.2.14 on 2026-05-28 14:04

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cashier", "0001_initial"),
        ("stores", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CashBox",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "name",
                    models.CharField(help_text="Cashbox display name.", max_length=255),
                ),
                (
                    "current_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Current calculated cashbox balance.",
                        max_digits=14,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this cashbox is active."
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        help_text="Branch this cashbox belongs to.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cashboxes",
                        to="stores.branch",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CashTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("INCOME", "Income"),
                            ("EXPENSE", "Expense"),
                            ("SALE", "Sale"),
                            ("PURCHASE", "Purchase"),
                            ("REFUND", "Refund"),
                            ("ADJUSTMENT", "Adjustment"),
                        ],
                        help_text="Financial transaction type.",
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Transaction amount. Adjustments may be positive or negative.",
                        max_digits=14,
                    ),
                ),
                (
                    "reference_type",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="External or internal object type this transaction refers to.",
                        max_length=64,
                    ),
                ),
                (
                    "reference_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="UUID of the related object, when available.",
                        null=True,
                    ),
                ),
                ("note", models.TextField(blank=True, help_text="Transaction note.")),
                (
                    "cashbox",
                    models.ForeignKey(
                        help_text="Cashbox affected by this transaction.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="finance.cashbox",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this transaction.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cash_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DailyClosing",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "total_sales",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total sales during the closing period.",
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "total_expenses",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total expenses during the closing period.",
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "total_income",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total additional income during the closing period.",
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "expected_cash",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Expected cash amount at close.",
                        max_digits=14,
                    ),
                ),
                (
                    "actual_cash",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Manually counted cash amount.",
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "difference",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Difference between actual and expected cash.",
                        max_digits=14,
                    ),
                ),
                (
                    "closed_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Date and time when the closing was completed.",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        help_text="Branch being closed.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="daily_closings",
                        to="stores.branch",
                    ),
                ),
                (
                    "cashier",
                    models.ForeignKey(
                        help_text="Cashier responsible for this closing.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="daily_closings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cashier_shift",
                    models.OneToOneField(
                        blank=True,
                        help_text="Closed cashier shift attached to this daily closing.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="daily_closing",
                        to="cashier.cashiershift",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ExpenseCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Expense category name.", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Expense category details."),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
                "indexes": [
                    models.Index(fields=["name"], name="finance_exp_name_11f00e_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("deleted_at__isnull", True)),
                        fields=("name",),
                        name="unique_active_expense_category_name",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Expense amount.",
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("note", models.TextField(blank=True, help_text="Expense note.")),
                (
                    "expense_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Expense date and time.",
                    ),
                ),
                (
                    "cashbox",
                    models.ForeignKey(
                        help_text="Cashbox used for the expense.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expenses",
                        to="finance.cashbox",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who recorded this expense.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expenses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Expense category.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expenses",
                        to="finance.expensecategory",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Income",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Income amount.",
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        help_text="Income source, such as owner deposit or other revenue.",
                        max_length=255,
                    ),
                ),
                ("note", models.TextField(blank=True, help_text="Income note.")),
                (
                    "income_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Income date and time.",
                    ),
                ),
                (
                    "cashbox",
                    models.ForeignKey(
                        help_text="Cashbox receiving this income.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incomes",
                        to="finance.cashbox",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who recorded this income.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incomes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="cashbox",
            index=models.Index(
                fields=["branch", "is_active"], name="finance_cas_branch__0e4531_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cashbox",
            index=models.Index(fields=["name"], name="finance_cas_name_0b20d3_idx"),
        ),
        migrations.AddConstraint(
            model_name="cashbox",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("branch", "name"),
                name="unique_active_cashbox_name_per_branch",
            ),
        ),
        migrations.AddIndex(
            model_name="cashtransaction",
            index=models.Index(
                fields=["cashbox", "created_at"], name="finance_cas_cashbox_b50f41_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cashtransaction",
            index=models.Index(
                fields=["transaction_type", "created_at"],
                name="finance_cas_transac_0270a9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cashtransaction",
            index=models.Index(
                fields=["reference_type", "reference_id"],
                name="finance_cas_referen_275ca8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cashtransaction",
            index=models.Index(
                fields=["created_by", "created_at"],
                name="finance_cas_created_a4ae5e_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="cashtransaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("deleted_at__isnull", True),
                    ("reference_id__isnull", False),
                    ("reference_type__gt", ""),
                ),
                fields=("transaction_type", "reference_type", "reference_id"),
                name="unique_active_cash_transaction_reference",
            ),
        ),
        migrations.AddIndex(
            model_name="dailyclosing",
            index=models.Index(
                fields=["branch", "closed_at"], name="finance_dai_branch__c1f6b3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dailyclosing",
            index=models.Index(
                fields=["cashier", "closed_at"], name="finance_dai_cashier_9f6ccf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["cashbox", "expense_date"],
                name="finance_exp_cashbox_70e7c1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["category", "expense_date"],
                name="finance_exp_categor_b624d6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["created_by", "expense_date"],
                name="finance_exp_created_62550c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="income",
            index=models.Index(
                fields=["cashbox", "income_date"], name="finance_inc_cashbox_1195c9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="income",
            index=models.Index(fields=["source"], name="finance_inc_source_3ec98e_idx"),
        ),
        migrations.AddIndex(
            model_name="income",
            index=models.Index(
                fields=["created_by", "income_date"],
                name="finance_inc_created_a78407_idx",
            ),
        ),
    ]
