# Generated by Django 5.2.14 on 2026-05-28 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cashbox",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "cash box",
                "verbose_name_plural": "cash boxes",
            },
        ),
        migrations.AlterModelOptions(
            name="cashtransaction",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "cash transaction",
                "verbose_name_plural": "cash transactions",
            },
        ),
        migrations.AlterModelOptions(
            name="dailyclosing",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "daily closing",
                "verbose_name_plural": "daily closings",
            },
        ),
        migrations.AlterModelOptions(
            name="expense",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "expense",
                "verbose_name_plural": "expenses",
            },
        ),
        migrations.AlterModelOptions(
            name="expensecategory",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "expense category",
                "verbose_name_plural": "expense categories",
            },
        ),
        migrations.AlterModelOptions(
            name="income",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "income",
                "verbose_name_plural": "incomes",
            },
        ),
    ]
