# Generated by Django 5.2.14 on 2026-05-29 04:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "finance",
            "0002_alter_cashbox_options_alter_cashtransaction_options_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="cashtransaction",
            index=models.Index(
                fields=["cashbox", "transaction_type", "created_at"],
                name="finance_cas_cashbox_efa1d1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["cashbox", "category", "expense_date"],
                name="finance_exp_cashbox_978148_idx",
            ),
        ),
    ]
