# Generated by Django 5.2.14 on 2026-05-28 13:31

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stores", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CashierShift",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "opened_at",
                    models.DateTimeField(help_text="Shift opening date and time."),
                ),
                (
                    "closed_at",
                    models.DateTimeField(
                        blank=True, help_text="Shift closing date and time.", null=True
                    ),
                ),
                (
                    "opening_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Cash amount at shift opening.",
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "closing_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Counted cash amount at shift close.",
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "expected_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Expected cash balance calculated from cash payments.",
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "difference",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Difference between counted and expected cash.",
                        max_digits=14,
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        help_text="Branch where the shift is opened.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cashier_shifts",
                        to="stores.branch",
                    ),
                ),
                (
                    "cashier",
                    models.ForeignKey(
                        help_text="Cashier who owns this shift.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cashier_shifts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["cashier", "opened_at"],
                        name="cashier_cas_cashier_dc3991_idx",
                    ),
                    models.Index(
                        fields=["branch", "opened_at"],
                        name="cashier_cas_branch__465dc6_idx",
                    ),
                    models.Index(
                        fields=["closed_at"], name="cashier_cas_closed__1b9308_idx"
                    ),
                ],
            },
        ),
    ]
