# Generated by Django 5.2.14 on 2026-05-28 13:19

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("inventory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "company_name",
                    models.CharField(
                        help_text="Supplier company or trade name.", max_length=255
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True,
                        help_text="Primary supplier contact person.",
                        max_length=255,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, help_text="Primary phone number.", max_length=32
                    ),
                ),
                (
                    "extra_phone",
                    models.CharField(
                        blank=True, help_text="Additional phone number.", max_length=32
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, help_text="Supplier email address.", max_length=254
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, help_text="Supplier address."),
                ),
                (
                    "inn_or_tax_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Supplier INN or tax identification number.",
                        max_length=64,
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Internal supplier notes."),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Current debt owed to this supplier.",
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether the supplier is active."
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["company_name"], name="purchases_s_company_afd7cf_idx"
                    ),
                    models.Index(
                        fields=["full_name"], name="purchases_s_full_na_8afabe_idx"
                    ),
                    models.Index(fields=["phone"], name="purchases_s_phone_9eb47a_idx"),
                    models.Index(
                        fields=["inn_or_tax_number"],
                        name="purchases_s_inn_or__79d04a_idx",
                    ),
                    models.Index(
                        fields=["is_active"], name="purchases_s_is_acti_4a355f_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        db_index=True,
                        help_text="Supplier invoice number.",
                        max_length=128,
                    ),
                ),
                (
                    "purchase_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Purchase date and time.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("CONFIRMED", "Confirmed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        help_text="Current purchase workflow status.",
                        max_length=20,
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Sum of purchase item totals before discount and tax.",
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Purchase-level discount amount.",
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Purchase-level tax amount.",
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Final purchase amount after discount and tax.",
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Amount already paid for this purchase.",
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "remaining_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Remaining debt for this purchase.",
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("note", models.TextField(blank=True, help_text="Purchase note.")),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time when the purchase was confirmed.",
                        null=True,
                    ),
                ),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who confirmed the purchase.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="confirmed_purchases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created the purchase.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_purchases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        help_text="Warehouse that receives purchased products.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchases",
                        to="inventory.warehouse",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        help_text="Supplier for this purchase.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchases",
                        to="purchases.supplier",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SupplierContact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "full_name",
                    models.CharField(help_text="Contact full name.", max_length=255),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True, help_text="Contact position.", max_length=255
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, help_text="Contact phone number.", max_length=32
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, help_text="Contact email address.", max_length=254
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        help_text="Supplier this contact belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="purchases.supplier",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SupplierPayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Payment amount.",
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("CARD", "Card"),
                            ("BANK_TRANSFER", "Bank transfer"),
                            ("CLICK", "Click"),
                            ("PAYME", "Payme"),
                            ("OTHER", "Other"),
                        ],
                        default="CASH",
                        help_text="Payment method used.",
                        max_length=32,
                    ),
                ),
                ("note", models.TextField(blank=True, help_text="Payment note.")),
                (
                    "paid_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Payment date and time.",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this supplier payment.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supplier_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        help_text="Supplier receiving the payment.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="purchases.supplier",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PurchaseItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Purchased quantity.",
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.001"))
                        ],
                    ),
                ),
                (
                    "purchase_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Unit purchase price.",
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Calculated item total.",
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True,
                        help_text="Optional expiry date for products that expire.",
                        null=True,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Purchased product.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_items",
                        to="catalog.product",
                    ),
                ),
                (
                    "purchase",
                    models.ForeignKey(
                        help_text="Purchase this item belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="purchases.purchase",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["purchase", "product"],
                        name="purchases_p_purchas_00688d_idx",
                    ),
                    models.Index(
                        fields=["product", "expiry_date"],
                        name="purchases_p_product_02b0af_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PurchasePayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Payment amount.",
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("CARD", "Card"),
                            ("BANK_TRANSFER", "Bank transfer"),
                            ("CLICK", "Click"),
                            ("PAYME", "Payme"),
                            ("OTHER", "Other"),
                        ],
                        default="CASH",
                        help_text="Payment method used.",
                        max_length=32,
                    ),
                ),
                ("note", models.TextField(blank=True, help_text="Payment note.")),
                (
                    "paid_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Payment date and time.",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this purchase payment.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchase_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "purchase",
                    models.ForeignKey(
                        help_text="Purchase this payment belongs to.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="purchases.purchase",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["purchase", "paid_at"],
                        name="purchases_p_purchas_8c3088_idx",
                    ),
                    models.Index(
                        fields=["payment_method", "paid_at"],
                        name="purchases_p_payment_963e22_idx",
                    ),
                    models.Index(
                        fields=["created_by", "paid_at"],
                        name="purchases_p_created_fcbc13_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="purchase",
            index=models.Index(
                fields=["invoice_number"], name="purchases_p_invoice_0b2ed5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchase",
            index=models.Index(
                fields=["status", "purchase_date"], name="purchases_p_status_a05d53_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchase",
            index=models.Index(
                fields=["supplier", "status"], name="purchases_p_supplie_4fc46d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchase",
            index=models.Index(
                fields=["warehouse", "status"], name="purchases_p_warehou_be3930_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchase",
            index=models.Index(
                fields=["created_by", "created_at"],
                name="purchases_p_created_430484_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchase",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("invoice_number",),
                name="unique_active_purchase_invoice_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchase",
            constraint=models.CheckConstraint(
                condition=models.Q(("subtotal__gte", Decimal("0.00"))),
                name="purchase_subtotal_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchase",
            constraint=models.CheckConstraint(
                condition=models.Q(("discount__gte", Decimal("0.00"))),
                name="purchase_discount_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchase",
            constraint=models.CheckConstraint(
                condition=models.Q(("tax_amount__gte", Decimal("0.00"))),
                name="purchase_tax_amount_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchase",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_amount__gte", Decimal("0.00"))),
                name="purchase_total_amount_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchase",
            constraint=models.CheckConstraint(
                condition=models.Q(("paid_amount__gte", Decimal("0.00"))),
                name="purchase_paid_amount_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchase",
            constraint=models.CheckConstraint(
                condition=models.Q(("remaining_amount__gte", Decimal("0.00"))),
                name="purchase_remaining_amount_non_negative",
            ),
        ),
        migrations.AddIndex(
            model_name="suppliercontact",
            index=models.Index(
                fields=["supplier", "full_name"], name="purchases_s_supplie_db1bbb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="suppliercontact",
            index=models.Index(fields=["phone"], name="purchases_s_phone_babff1_idx"),
        ),
        migrations.AddIndex(
            model_name="suppliercontact",
            index=models.Index(fields=["email"], name="purchases_s_email_d24ef7_idx"),
        ),
        migrations.AddIndex(
            model_name="supplierpayment",
            index=models.Index(
                fields=["supplier", "paid_at"], name="purchases_s_supplie_16389e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplierpayment",
            index=models.Index(
                fields=["payment_method", "paid_at"],
                name="purchases_s_payment_58afb4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="supplierpayment",
            index=models.Index(
                fields=["created_by", "paid_at"], name="purchases_s_created_047726_idx"
            ),
        ),
    ]
