# Generated by Django 5.2.14 on 2026-05-28 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
        ("purchases", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="supplierpayment",
            name="cashbox",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional cashbox used for this supplier debt payment.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="supplier_payments",
                to="finance.cashbox",
            ),
        ),
        migrations.AddIndex(
            model_name="supplierpayment",
            index=models.Index(
                fields=["cashbox", "paid_at"], name="purchases_s_cashbox_be2832_idx"
            ),
        ),
    ]
