# Generated by Django 5.2.14 on 2026-05-29 04:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_stock_inventory_s_warehou_1119b6_idx_and_more"),
        ("purchases", "0002_supplierpayment_cashbox_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="purchase",
            index=models.Index(
                fields=["supplier", "status", "purchase_date"],
                name="purchases_p_supplie_caf41a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="purchase",
            index=models.Index(
                fields=["warehouse", "status", "purchase_date"],
                name="purchases_p_warehou_803659_idx",
            ),
        ),
    ]
