# Generated by Django 5.2.14 on 2026-05-28 18:30

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("stores", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessPermission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Stable permission code, for example reports.view.",
                        max_length=128,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Readable permission name.", max_length=255
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        blank=True,
                        help_text="Application module this permission belongs to.",
                        max_length=64,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional permission description."
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "access permission",
                "verbose_name_plural": "access permissions",
                "ordering": ("module", "code"),
                "abstract": False,
                "indexes": [
                    models.Index(fields=["code"], name="accounts_ac_code_8f1c1b_idx"),
                    models.Index(
                        fields=["module", "is_active"],
                        name="accounts_ac_module_eddf0b_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FailedLoginAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("identifier", models.CharField(db_index=True, max_length=255)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("failure_reason", models.CharField(blank=True, max_length=255)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "failed login attempt",
                "verbose_name_plural": "failed login attempts",
                "ordering": ("-created_at",),
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["identifier", "created_at"],
                        name="accounts_fa_identif_feb9b2_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "created_at"],
                        name="accounts_fa_ip_addr_65f8c0_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PermissionGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("code", models.CharField(max_length=128, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "permissions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="permission_groups",
                        to="accounts.accesspermission",
                    ),
                ),
            ],
            options={
                "verbose_name": "permission group",
                "verbose_name_plural": "permission groups",
                "ordering": ("name",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Stable role code, for example owner, admin, manager, or cashier.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "is_system",
                    models.BooleanField(
                        default=False,
                        help_text="System roles are the built-in owner/admin/manager/cashier roles.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "permission_groups",
                    models.ManyToManyField(
                        blank=True, related_name="roles", to="accounts.permissiongroup"
                    ),
                ),
                (
                    "permissions",
                    models.ManyToManyField(
                        blank=True, related_name="roles", to="accounts.accesspermission"
                    ),
                ),
            ],
            options={
                "verbose_name": "role",
                "verbose_name_plural": "roles",
                "ordering": ("name",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SystemInstallation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "installation_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Local installation identifier for future central admin sync.",
                        unique=True,
                    ),
                ),
                (
                    "license_key",
                    models.CharField(
                        blank=True,
                        help_text="Placeholder for a future central license key.",
                        max_length=255,
                    ),
                ),
                (
                    "subscription_status",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("trial", "Trial"),
                            ("active", "Active"),
                            ("past_due", "Past due"),
                            ("suspended", "Suspended"),
                        ],
                        default="unknown",
                        help_text="Placeholder subscription state for future central licensing.",
                        max_length=32,
                    ),
                ),
                (
                    "last_check_in",
                    models.DateTimeField(
                        blank=True,
                        help_text="Placeholder for the last future central admin check-in.",
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "system installation",
                "verbose_name_plural": "system installations",
                "ordering": ("-created_at",),
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["installation_id"],
                        name="accounts_sy_install_660192_idx",
                    ),
                    models.Index(
                        fields=["subscription_status", "is_active"],
                        name="accounts_sy_subscri_17a136_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        help_text="Profile avatar image.",
                        null=True,
                        upload_to="accounts/avatars/",
                    ),
                ),
                (
                    "employee_code",
                    models.CharField(
                        blank=True,
                        help_text="Internal employee code.",
                        max_length=64,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True,
                        help_text="Employee position or job title.",
                        max_length=128,
                    ),
                ),
                (
                    "biography",
                    models.TextField(blank=True, help_text="Short employee biography."),
                ),
                (
                    "language",
                    models.CharField(
                        default="en",
                        help_text="Preferred interface language code.",
                        max_length=16,
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="Asia/Tashkent",
                        help_text="Preferred timezone name.",
                        max_length=64,
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("system", "System"),
                            ("light", "Light"),
                            ("dark", "Dark"),
                        ],
                        default="system",
                        help_text="Preferred interface theme.",
                        max_length=16,
                    ),
                ),
                (
                    "notification_preferences",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Per-channel notification preferences.",
                    ),
                ),
                (
                    "employee_status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("on_leave", "On leave"),
                        ],
                        default="active",
                        help_text="Current employee status.",
                        max_length=24,
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Internal employee notes."),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        help_text="Primary branch assignment.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employee_profiles",
                        to="stores.branch",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="User account this employee profile belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "user profile",
                "verbose_name_plural": "user profiles",
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserRoleAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional branch scope for this role assignment.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_assignments",
                        to="stores.branch",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="accounts.role",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "user role assignment",
                "verbose_name_plural": "user role assignments",
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AccountSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "session_key",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                (
                    "token_jti",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("device_name", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "last_seen_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("logged_out_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "account session",
                "verbose_name_plural": "account sessions",
                "ordering": ("-created_at",),
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="accounts_ac_user_id_a705e1_idx",
                    ),
                    models.Index(
                        fields=["token_jti"], name="accounts_ac_token_j_f4eea1_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("sale", "Sale"),
                            ("purchase", "Purchase"),
                            ("refund", "Refund"),
                            ("stock", "Stock"),
                            ("finance", "Finance"),
                            ("admin", "Admin"),
                            ("security", "Security"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        blank=True,
                        help_text="Model or domain object type touched by the action.",
                        max_length=128,
                    ),
                ),
                ("entity_id", models.UUIDField(blank=True, null=True)),
                ("object_repr", models.CharField(blank=True, max_length=255)),
                ("summary", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "audit log",
                "verbose_name_plural": "audit logs",
                "ordering": ("-created_at",),
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["actor", "action", "created_at"],
                        name="accounts_au_actor_i_49ae84_idx",
                    ),
                    models.Index(
                        fields=["entity_type", "entity_id"],
                        name="accounts_au_entity__473722_idx",
                    ),
                    models.Index(
                        fields=["action", "created_at"],
                        name="accounts_au_action_c683b9_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="LoginHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "identifier",
                    models.CharField(
                        blank=True,
                        help_text="Submitted login identifier, usually email.",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Success"), ("failed", "Failed")],
                        max_length=16,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("failure_reason", models.CharField(blank=True, max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="login_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "login history",
                "verbose_name_plural": "login history",
                "ordering": ("-created_at",),
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["user", "status", "created_at"],
                        name="accounts_lo_user_id_7ddb56_idx",
                    ),
                    models.Index(
                        fields=["identifier", "status", "created_at"],
                        name="accounts_lo_identif_8fde5c_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="permissiongroup",
            index=models.Index(fields=["code"], name="accounts_pe_code_e36976_idx"),
        ),
        migrations.AddIndex(
            model_name="permissiongroup",
            index=models.Index(
                fields=["is_active"], name="accounts_pe_is_acti_ae6c19_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(fields=["code"], name="accounts_ro_code_5aeee6_idx"),
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(
                fields=["is_active", "is_system"], name="accounts_ro_is_acti_e281d9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(
                fields=["employee_code"], name="accounts_us_employe_b790ef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(
                fields=["branch", "employee_status"],
                name="accounts_us_branch__d39992_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="userroleassignment",
            index=models.Index(
                fields=["user", "is_active"], name="accounts_us_user_id_55ae20_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userroleassignment",
            index=models.Index(
                fields=["role", "is_active"], name="accounts_us_role_id_e1094b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userroleassignment",
            index=models.Index(
                fields=["branch", "is_active"], name="accounts_us_branch__3cd110_idx"
            ),
        ),
    ]
